from http.client import responses

import feedparser
import smtplib
import google.generativeai as genai
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

from config import GOOGLE_API_KEY, EMAIL_SENDER, EMAIL_RECEIVER, EMAIL_PASSWORD

RSS_FEEDS = {
    "TechCrunch": "https://techcrunch.com/feed/",
    "The Verge": "https://www.theverge.com/rss/index.xml",
    "Hacker News": "https://news.ycombinator.com/rss",
    "BBC World": "http://feeds.bbci.co.uk/news/world/rss.xml"
}

genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')

def get_summaries():
    """Fetches and summarizes news items"""
    briefing_content = ""

    for source,url in RSS_FEEDS.items():
        feed = feedparser.parse(url)
        top_articles = feed.entries[:4]

        briefing_content += f"<h2>Lastest from {source}</h2>\n"

        for article in top_articles:
            prompt = f"Summarize this news title and snippet in one concise sentence: {article.title} - {article.desciption}"
            try:
                response =  model.generate_content(prompt)
                summary = response.text.strip()
            except:
                summary = article.title

            briefing_content += f"""
                        <div style="margin-bottom: 15px; border-left: 4px solid #007bff; padding-left: 10px;">
                            <h3 style="margin: 0;"><a href="{article.link}" style="text-decoration: none; color: #333;">{article.title}</a></h3>
                            <p style="color: #555; font-style: italic; margin-top: 5px;">{summary}</p>
                        </div>
                        """

    return briefing_content

def send_email(content):
    """Send an email"""
    msg = MIMEMultipart("alternative")
    msg["From"] = "Ai news agent <"+ EMAIL_SENDER +">"
    msg["To"] = EMAIL_RECEIVER
    msg["Subject"] = f"🌍 Morning Briefing: {datetime.now().strftime('%Y-%m-%d')}"

    html_body = f"""
        <html>
          <body style="font-family: Arial, sans-serif; line-height: 1.6;">
            <h1 style="color: #2c3e50;">Good Morning! Here is your update.</h1>
            <hr>
            {content}
            <hr>
            <p style="font-size: 12px; color: #999;">Generated by your Personal AI Agent</p>
          </body>
        </html>
        """
    msg.attach(MIMEText(html_body, 'html'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.send_message(msg)
        server.quit()
        print("✅Email sent!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

if __name__ == "__main__":
    print("🤖 Agent waking up...")
    news_html = get_summaries()
    send_email(news_html)
    print("💤 Agent going back to sleep.")
